### ISSUE TITLE
permutation([1]) returns nothing -> should return [1]

### ISSUE THREAD

**Issue by matthiasg** [zoubin/array-permutation#1]
For automated tests it is sometimes helpful to generate interesting arrays automatically. permutations should return the single permutation possible for arrays of length 1

**Comment by zoubin** [comment]
Oh, I just `return`ed rather than `yield`ed when `[1]` is given as the input!
It's fixed in the latest release 0.2.1.
Thanks!

**Comment by matthiasg** [comment]
Thanks
